
import React, { useState, useMemo, useCallback, useRef, useEffect } from 'react';
import { USD_CONFIG, SUPPORTED_CURRENCIES } from './constants';
import { CurrencyConfig, CashRecord } from './types';
import DenominationInput from './components/DenominationInput';
import CurrencyConverter from './components/CurrencyConverter';
import AIAssistant, { AIAssistantRef } from './components/AIAssistant';
import { currencyService, ExchangeRates } from './services/currencyService';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';

function App() {
  const [currency, setCurrency] = useState<CurrencyConfig>(USD_CONFIG);
  const [counts, setCounts] = useState<Record<string, number>>({});
  const [history, setHistory] = useState<CashRecord[]>(() => {
    try {
      const saved = localStorage.getItem('procash_history');
      return saved ? JSON.parse(saved) : [];
    } catch (e) {
      console.error('Failed to load history', e);
      return [];
    }
  });

  useEffect(() => {
    localStorage.setItem('procash_history', JSON.stringify(history));
  }, [history]);

  const [isLiveActive, setIsLiveActive] = useState(false);
  const [showAssistant, setShowAssistant] = useState(false);
  const [lastUpdatedId, setLastUpdatedId] = useState<string | null>(null);
  const [exchangeRates, setExchangeRates] = useState<ExchangeRates | null>(null);
  
  const aiAssistantRef = useRef<AIAssistantRef>(null);

  useEffect(() => {
    const fetchRates = async () => {
      const rates = await currencyService.getRates(currency.code);
      setExchangeRates(rates);
    };
    fetchRates();
  }, [currency.code]);

  const sendEmailReport = (date: string, records: CashRecord[], dayTotal: number) => {
    const subject = `Daily Cash Report - ${date}`;
    let body = `ProCash AI - Daily Report\nDate: ${date}\n\n`;
    body += `Total Consolidated Balance: ${currency.symbol}${dayTotal.toLocaleString(undefined, { minimumFractionDigits: 2 })}\n`;
    body += `Transaction Count: ${records.length}\n\n`;
    body += `--- Transactions ---\n`;
    
    records.forEach(r => {
      const time = new Date(r.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      body += `[${time}] ${currency.symbol}${r.total.toLocaleString(undefined, { minimumFractionDigits: 2 })}\n`;
      
      // Add a brief breakdown of the largest denomination in this transaction for context
      const largestDenom = Object.entries(r.counts)
        .filter(([_, count]) => count > 0)
        .map(([id, count]) => {
           const d = currency.denominations.find(d => d.id === id);
           return d ? { label: d.label, value: d.value * count } : null;
        })
        .filter(item => item !== null)
        .sort((a, b) => (b?.value || 0) - (a?.value || 0))[0];

      if (largestDenom) {
         body += `       (Mainly: ${largestDenom.label})\n`;
      }
    });

    body += `\n\nGenerated by ProCash AI`;
    
    const mailtoLink = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoLink;
  };

  const handleCountChange = useCallback((id: string, value: number) => {
    setCounts(prev => ({ ...prev, [id]: value }));
    // Trigger visual feedback
    setLastUpdatedId(id);
    setTimeout(() => setLastUpdatedId(null), 1000);
  }, []);

  const handleAICommand = useCallback((cmd: { action: string; label?: string; count?: number }) => {
    if (cmd.action === 'clear') {
      setCounts({});
      return;
    }

    if (cmd.label) {
      // Robust matching: find the best match based on the label provided by AI
      const searchStr = cmd.label.toLowerCase().replace(/[^0-9]/g, '');
      
      const denom = currency.denominations.find(d => {
        const labelLower = d.label.toLowerCase();
        const valueStr = d.value.toString();
        
        return (
          labelLower === cmd.label?.toLowerCase() ||
          labelLower.includes(cmd.label?.toLowerCase() || '') ||
          (searchStr && valueStr === searchStr) ||
          (searchStr && labelLower.includes(searchStr))
        );
      });

      if (denom) {
        const amount = cmd.count || 0;
        if (cmd.action === 'set') {
          handleCountChange(denom.id, amount);
        } else if (cmd.action === 'add') {
          setCounts(prev => {
            const newCount = (prev[denom.id] || 0) + amount;
            setLastUpdatedId(denom.id);
            setTimeout(() => setLastUpdatedId(null), 1000);
            return { ...prev, [denom.id]: newCount };
          });
        }
      }
    }
  }, [currency, handleCountChange]);

  const total = useMemo(() => {
    return currency.denominations.reduce((acc, denom) => acc + (counts[denom.id] || 0) * denom.value, 0);
  }, [currency, counts]);

  const chartData = useMemo(() => {
    return currency.denominations
      .filter(d => (counts[d.id] || 0) > 0)
      .map(d => ({
        name: d.label,
        value: (counts[d.id] || 0) * d.value,
        color: d.type === 'bill' ? '#10b981' : '#f59e0b'
      }))
      .sort((a, b) => b.value - a.value);
  }, [currency, counts]);

  const groupedHistory = useMemo(() => {
    const groups: Record<string, { date: string, records: CashRecord[], dayTotal: number }> = {};
    history.forEach(record => {
      const dateKey = new Date(record.timestamp).toLocaleDateString(undefined, {
        year: 'numeric', month: 'long', day: 'numeric'
      });
      if (!groups[dateKey]) groups[dateKey] = { date: dateKey, records: [], dayTotal: 0 };
      groups[dateKey].records.push(record);
      groups[dateKey].dayTotal += record.total;
    });
    return Object.values(groups).sort((a, b) => b.records[0].timestamp - a.records[0].timestamp);
  }, [history]);

  const saveRecord = () => {
    if (total === 0) return;
    const record: CashRecord = {
      id: Math.random().toString(36).substr(2, 9),
      timestamp: Date.now(),
      currency: currency.code,
      counts: { ...counts },
      total,
    };
    setHistory([record, ...history]);
  };

  const toggleVoiceControl = () => {
    setShowAssistant(prev => !prev);
    // If we are opening it, we don't necessarily start live mode immediately, 
    // but the user can click the button inside. 
    // Or if the user wants "Voice Command" to start listening immediately:
    // if (!showAssistant) aiAssistantRef.current?.toggleLive();
  };

  return (
    <div className="flex h-screen overflow-hidden bg-slate-50 relative">
      <main className="flex-1 flex flex-col min-w-0 relative z-10">
        <header className="h-auto py-4 glass border-b border-slate-200 px-4 flex flex-col gap-4 shrink-0 relative z-20">
          <div className="flex items-center justify-between w-full">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 mesh-gradient rounded-xl flex items-center justify-center text-white font-black text-xl shadow-lg shadow-indigo-200">
                P
              </div>
              <div>
                <h1 className="font-extrabold text-slate-900 tracking-tight text-lg">ProCash <span className="text-indigo-600">AI</span></h1>
              </div>
            </div>
            
            <div className="flex items-center gap-2">
               <div className="flex items-center gap-1 bg-white px-3 py-1.5 rounded-xl border border-slate-200 shadow-sm">
                 <select 
                  value={currency.code}
                  onChange={(e) => {
                    const found = SUPPORTED_CURRENCIES.find(c => c.code === e.target.value);
                    if (found) setCurrency(found);
                    setCounts({});
                  }}
                  className="bg-transparent border-none outline-none text-xs font-extrabold text-slate-800 cursor-pointer w-16"
                >
                  {SUPPORTED_CURRENCIES.map(c => <option key={c.code} value={c.code}>{c.code}</option>)}
                </select>
              </div>
              <button 
                onClick={() => confirm('Reset current session?') && setCounts({})}
                className="p-2 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-xl transition-all"
              >
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>
              </button>
            </div>
          </div>

          {/* Mobile Header Balance */}
          <div className="flex flex-col items-center justify-center py-2 bg-white/50 rounded-2xl border border-white/50 shadow-sm">
             <span className="text-[9px] font-black text-slate-400 uppercase tracking-[0.3em] mb-1">Consolidated Balance</span>
             <div className="text-4xl font-black text-slate-900 font-mono tracking-tighter">
                <span className="text-indigo-600 mr-1">{currency.symbol}</span>
                {total.toLocaleString(undefined, { minimumFractionDigits: 2 })}
             </div>
          </div>
        </header>

        <div className="flex-1 overflow-y-auto p-4 space-y-6 pb-24">
          <section className="space-y-4">
            <div className="flex items-center justify-between px-1">
              <h2 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Asset Breakdown</h2>
              <span className="text-[10px] font-extrabold text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-full">{currency.code}</span>
            </div>
            <div className="grid grid-cols-1 gap-3">
              {currency.denominations.map(denom => (
                <div key={denom.id} className={lastUpdatedId === denom.id ? 'animate-[pulse_1s_ease-in-out]' : ''}>
                  <DenominationInput
                    denom={denom}
                    count={counts[denom.id] || 0}
                    symbol={currency.symbol}
                    onChange={(val) => handleCountChange(denom.id, val)}
                  />
                </div>
              ))}
            </div>
          </section>

          <aside className="space-y-6">
            <div className="mesh-gradient rounded-[2rem] p-6 text-white shadow-xl shadow-indigo-200 relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-48 h-48 bg-white/10 rounded-full blur-3xl -mr-24 -mt-24"></div>
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-black uppercase tracking-[0.3em] opacity-60">Vault Action</span>
                <button className="p-2 bg-white/10 hover:bg-white/20 rounded-xl transition-all">
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg>
                </button>
              </div>
              <div className="mt-6">
                <button 
                  onClick={saveRecord} 
                  disabled={total === 0}
                  className="w-full bg-white text-indigo-900 hover:text-indigo-600 py-3 rounded-xl text-xs font-black uppercase tracking-widest transition-all disabled:opacity-30 disabled:cursor-not-allowed shadow-lg"
                >
                  Commit to Vault
                </button>
              </div>
            </div>

            <CurrencyConverter initialCurrency={currency.code} />

            {/* Exchange Rates Display */}
            {total > 0 && exchangeRates && (
              <div className="bg-white rounded-[2rem] p-6 border border-slate-100 shadow-lg">
                <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.25em] mb-4 flex items-center gap-2">
                  Equivalent Values
                  <div className="h-px flex-1 bg-slate-100"></div>
                </h3>
                <div className="space-y-3">
                  {SUPPORTED_CURRENCIES.filter(c => c.code !== currency.code).map(targetCurrency => {
                    const rate = exchangeRates.rates[targetCurrency.code];
                    if (!rate) return null;
                    const convertedValue = total * rate;
                    return (
                      <div key={targetCurrency.code} className="flex items-center justify-between p-3 bg-slate-50/50 rounded-xl border border-slate-100">
                        <div className="flex items-center gap-3">
                          <div className="w-8 h-8 rounded-full bg-white shadow-sm flex items-center justify-center text-[10px] font-black text-slate-500 border border-slate-100">
                            {targetCurrency.code}
                          </div>
                          <div className="flex flex-col">
                            <span className="text-[9px] font-bold text-slate-400 uppercase tracking-wider">Exchange Rate</span>
                            <span className="text-[10px] font-mono text-slate-500">1 {currency.code} = {rate.toFixed(4)} {targetCurrency.code}</span>
                          </div>
                        </div>
                        <div className="text-right">
                          <span className="block text-sm font-black text-slate-800 font-mono">
                            {targetCurrency.symbol}{convertedValue.toLocaleString(undefined, { maximumFractionDigits: 2 })}
                          </span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {chartData.length > 0 && (
              <div className="bg-white rounded-[2rem] p-6 border border-slate-100 shadow-lg">
                <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.25em] mb-6">
                  Diversification
                </h3>
                <div className="h-48 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={chartData} layout="vertical" margin={{ left: -10 }}>
                      <XAxis type="number" hide />
                      <YAxis dataKey="name" type="category" width={55} axisLine={false} tickLine={false} style={{ fontSize: '10px', fontWeight: 700, fill: '#64748b' }} />
                      <Tooltip 
                        cursor={{ fill: '#f8fafc', radius: 10 }}
                        contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)', padding: '8px', fontSize: '12px' }} 
                        formatter={(val: number) => [`${currency.symbol}${val.toLocaleString()}`, '']} 
                      />
                      <Bar dataKey="value" radius={[0, 8, 8, 0]} barSize={20}>
                        {chartData.map((entry, index) => <Cell key={`cell-${index}`} fill={entry.color} />)}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>
            )}

            <div className="bg-white rounded-[2rem] border border-slate-100 shadow-lg overflow-hidden flex flex-col">
              <div className="p-6 border-b border-slate-50 bg-slate-50/30 flex justify-between items-center">
                <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-[0.25em]">History</h3>
                <button 
                  onClick={() => history.length > 0 && confirm('Wipe audit history?') && setHistory([])}
                  className="text-[9px] font-black text-slate-400 hover:text-red-500 transition-colors uppercase tracking-widest"
                >
                  Clear
                </button>
              </div>
              <div className="p-4 space-y-4 max-h-80 overflow-y-auto">
                {groupedHistory.length === 0 && (
                  <div className="text-center py-10 opacity-20">
                    <p className="text-xs font-bold uppercase tracking-widest">No Logs</p>
                  </div>
                )}
                {groupedHistory.map(dayGroup => (
                  <div key={dayGroup.date} className="space-y-3">
                    <div className="flex items-center justify-between sticky top-0 bg-white/90 backdrop-blur-sm py-1 z-10">
                      <div className="flex items-center gap-2">
                        <h4 className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{dayGroup.date}</h4>
                        <button 
                          onClick={() => sendEmailReport(dayGroup.date, dayGroup.records, dayGroup.dayTotal)}
                          className="p-1 text-slate-300 hover:text-indigo-600 transition-colors"
                          title="Email Report"
                        >
                          <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                          </svg>
                        </button>
                      </div>
                      <span className="text-[10px] font-black text-indigo-600 font-mono">
                        {currency.symbol}{dayGroup.dayTotal.toLocaleString()}
                      </span>
                    </div>
                    <div className="space-y-2">
                      {dayGroup.records.map(record => (
                        <div key={record.id} className="flex items-center justify-between p-3 bg-slate-50 rounded-xl">
                          <div className="flex items-center gap-3">
                            <span className="text-[10px] font-black text-slate-400 tabular-nums">
                              {new Date(record.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                            </span>
                            <span className="text-xs font-extrabold text-slate-800 font-mono">
                              {record.total.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </aside>
        </div>
        
        {/* Floating Action Button for AI */}
        <button 
          onClick={toggleVoiceControl}
          className={`fixed bottom-6 right-6 w-14 h-14 rounded-full shadow-2xl flex items-center justify-center transition-all duration-300 z-40 ${
            isLiveActive 
            ? 'bg-red-500 text-white animate-pulse ring-4 ring-red-200' 
            : 'mesh-gradient text-white hover:scale-110'
          }`}
        >
          <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
          </svg>
        </button>
      </main>

      {/* AI Assistant Overlay */}
      {showAssistant && (
        <div className="fixed inset-0 z-50 flex flex-col bg-slate-50/95 backdrop-blur-xl animate-[slideUp_0.3s_ease-out]">
          <div className="flex items-center justify-between p-4 border-b border-slate-200">
            <h2 className="text-sm font-black text-slate-800 uppercase tracking-widest">AI Assistant</h2>
            <button 
              onClick={() => setShowAssistant(false)}
              className="p-2 bg-slate-200 rounded-full hover:bg-slate-300 transition-colors"
            >
              <svg className="w-5 h-5 text-slate-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <div className="flex-1 overflow-hidden">
            <AIAssistant 
              ref={aiAssistantRef}
              denominations={currency.denominations} 
              onCommand={handleAICommand} 
              onLiveStateChange={setIsLiveActive}
            />
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
